os: linux

dist: bionic

language: c

services:
    - docker

install:
    - ./make_dockerfile.sh
    - docker-compose build

script:
    - docker-compose run $(bash <(curl -s https://codecov.io/env)) tests

notifications:
    email:
        on_success: change
        on_failure: always

# keep in sync with codecov.yml number of builds
env:
    - PG_BRANCH=master TEST_CASE=tap
    - PG_BRANCH=master TEST_CASE=tap MODE=legacy
#    - PG_BRANCH=master TEST_CASE=all
    - PG_BRANCH=master TEST_CASE=all MODE=paranoia
    - PG_BRANCH=REL_14_STABLE TEST_CASE=tap
    - PG_BRANCH=REL_14_STABLE TEST_CASE=tap MODE=legacy
#    - PG_BRANCH=REL_14_STABLE TEST_CASE=all
    - PG_BRANCH=REL_14_STABLE TEST_CASE=all MODE=paranoia
    - PG_BRANCH=REL_13_STABLE TEST_CASE=tap
    - PG_BRANCH=REL_13_STABLE TEST_CASE=tap MODE=legacy
#    - PG_BRANCH=REL_13_STABLE TEST_CASE=all
    - PG_BRANCH=REL_13_STABLE TEST_CASE=all MODE=paranoia
    - PG_BRANCH=REL_12_STABLE TEST_CASE=tap
    - PG_BRANCH=REL_12_STABLE TEST_CASE=tap MODE=legacy
#    - PG_BRANCH=REL_12_STABLE TEST_CASE=all
    - PG_BRANCH=REL_12_STABLE TEST_CASE=all MODE=paranoia
    - PG_BRANCH=REL_11_STABLE TEST_CASE=tap
    - PG_BRANCH=REL_11_STABLE TEST_CASE=tap MODE=legacy
#    - PG_BRANCH=REL_11_STABLE TEST_CASE=all
    - PG_BRANCH=REL_11_STABLE TEST_CASE=all MODE=paranoia

jobs:
    allow_failures:
        - if: env(PG_BRANCH) = master

