os: linux

dist: bionic

language: c

services:
    - docker

install:
    - ./make_dockerfile.sh
    - docker-compose build

script:
    - docker-compose run $(bash <(curl -s https://codecov.io/env)) tests

notifications:
    email:
        on_success: change
        on_failure: always

# keep in sync with codecov.yml number of builds
env:
    - PG_BRANCH=REL_14_STABLE TEST_CASE=test_delta_vacuum_full MODE=paranoia

jobs:
    allow_failures:
        - if: env(PG_BRANCH) = master

